### ISSUE TITLE
Referring to data outside of the data frame?

### ISSUE THREAD

**Issue by jwhendy** [has2k1/plydata#30]
In R, I can do this:
```
library(dplyr)
df = data.frame(x=c("a", "a", "b", "b", "c"), y=c(1, 2, 3, 4, 5))

letters_of_interest = c("a", "c")
df %>% filter(x %in% letters_of_interest)
  x y
1 a 1
2 a 2
3 c 5
```

In plydata, I thought this would work:
```
import pandas as pd
from plydata import query
df = pd.DataFrame({'x': ['a', 'a', 'b', 'b', 'c'], 'y': [1, 2, 3, 4, 5]})
letters_of_interest = ['a', 'c']
df >> query('x.isin(letters_of_interest)')
# ...
KeyError: 'letters_of_interest'
pandas.core.computation.ops.UndefinedVariableError: name 'letters_of_interest' is not defined
```

Perhaps it's obvious, but on a whim I tried this, which does work:
```
 df >> query(f'x.isin({letters_of_interest})')
   x  y
0  a  1
1  a  2
4  c  5
```

Is there somewhere that what is quoted vs. what is not is systematized? Maybe I just haven't wrapped my head around it, but I find it hard to remember what needs quotes (e.g. `query('col_name == "foo"')`) vs. what is not (e.g. `summarize(new_col_name = 'np.mean(col_name')`). Is there a good way to identify that plydata needs quotes around and/or is the above obvious from the documentation somewhere (perhaps "pulling in variables from the dataframe are accessible, but external variables need to be string formatted")?

Thanks.

**Comment by has2k1** [comment]
For the `query` verb, when referring to variables in the environment, you should prefer to use the `@` symbol. e.g

```python
df >> query('x.isin(@letters_of_interest)')
```
Other verbs do not use `@`. This is because `query` is just `pandas.DataFrame.query`.

Plydata creates an environment where expressions can refer to columns in the dataframe as variables. To protect these expressions so that python does not execute them right away, you have to wrap them in strings. When you are creating a new column e.g. with `summarize`, the name of the new column is not part of what is executed (it is a just keyword argument name), but the value is an expression (a python statement that returns a value) that refers to a column in the dataframe so it has to be protected (as string) and executed in the our special environment.

**Comment by jwhendy** [comment]
Thanks for all the clarification, and I also learned about `@` which I hadn't seen before. Thanks very much, and really loving this package after learning about it, btw. I was surprised/excited to see it was also created by you after having used plotnine for maybe a year now. Thanks for making them both!
